django_twetter_app/django_twetter_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("twetterapp.urls")),
    path("",include("django.contrib.auth.urls"))
]

django_twetter_app/twetterapp/urls.py
from django.urls import path
from . import views

app_name = "twetterapp"

urlpatterns = [
    path("list",views.listtwet, name="listtwet"),
    path("add", views.addtwetter, name="addtwet"),
    path("singup",views.SingUpView.as_view(),name="singup"),
    path("delete/<int:id>",views.deletetwet, name="delete")
]

django_twetter_app/twetterapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    messange = models.CharField(max_length=50)

    def __str__(self):
        return f"Tweet User : {self.username} Messange : {self.messange}"

django_twetter_app/twetterapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

def listtwet(request):
    all_tweet = models.Tweet.objects.all()
    tweet_dic = {"tweets" : all_tweet}
    return render(request,"twetterapp/listtwet.html", context=tweet_dic)

@login_required(login_url="/login")
def addtwetter(request):
    if request.POST:
        message = request.POST["message"]
        models.Tweet.objects.create(username = request.user, messange = message)
        return redirect(reverse("twetterapp:listtwet"))
    else:
        return render(request,"twetterapp/addtwet.html")

@login_required
def deletetwet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect("twetterapp:listtwet")

class SingUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/singup.html"

django_twetter_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Twetter App</title>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
      </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Twetter App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'twetterapp:listtwet' %}">list</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'twetterapp:addtwet' %}">add twet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}?next=/list">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'twetterapp:singup' %}">Singup</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      {%block content%}
      {%endblock%}
</body>
</html>

django_twetter_app/twetterapp/templates/twetterapp/addtwet.html
{% extends "base.html" %}

{%block content%}
<h1>Add Twet</h1>
<form action="" method="POST">
    {% csrf_token %} 
    <!--
      <div class="mb-3">
      
        <label for="Nickname" class="form-label">Nick Name</label>
        <input type="text" class="form-control" id="nickname" name="nickname">
        
      </div>
    -->
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </form>
{%endblock%}

django_twetter_app/twetterapp/templates/twetterapp/listtwet.html
{% extends "base.html" %}

{%block content%}
<h1>List Twet</h1>
<ul>
    {% for tweet in tweets %}
    <li>{{tweet.username}}---{{tweet.messange}}</li>

    {%if tweet.username == user%}
    <a href="{% url 'twetterapp:delete' id=tweet.id %}" class="btn btn-danger" >delete</a>
    {%endif%}

    {%endfor%}
</ul>

{%endblock%}